#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


@dataclass(frozen=True)
class VariableRow:
    label: str
    name: str
    allowed_intervals: list[float | int]


@dataclass(frozen=True)
class ParameterThreshold:
    min_srd_distance: float | int
    min_abs_dist: float | int


@dataclass(frozen=True)
class SignalRow:
    column: int
    description: str
    signal: str


@dataclass(frozen=True)
class AppendixEnvironmentSpec:
    model_name: str
    low_description: str
    high_description: str
    initial_state_rows: tuple[VariableRow, ...]
    parameter_rows: tuple[VariableRow, ...]
    parameter_thresholds: Dict[str, ParameterThreshold]
    simulation_properties: Dict[str, float | int]
    signal_rows: tuple[SignalRow, ...]


def _parse_code_value(raw: str) -> Any:
    text = raw.strip()
    try:
        return ast.literal_eval(text)
    except Exception:
        try:
            return float(text)
        except ValueError:
            return text


def _normalize_description(text: str) -> str:
    stripped = text.strip()
    prefix = "These time series were generated by "
    if stripped.startswith(prefix):
        stripped = "by " + stripped[len(prefix) :]
    return stripped


def _parse_description(body: str, label: str, *, model_name: str) -> str:
    match = re.search(
        rf"\\textbf\{{{label}\}}\s*\\begin\{{DocCode\}}\s*(.*?)\s*\\end\{{DocCode\}}",
        body,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"{model_name}: missing {label} description in appendix")
    return _normalize_description(match.group(1))


def _parse_variable_rows(body: str, *, model_name: str) -> tuple[tuple[VariableRow, ...], tuple[VariableRow, ...]]:
    match = re.search(
        r"\\begin\{EnvironmentConfigTableNoMod\}(.*?)\\end\{EnvironmentConfigTableNoMod\}",
        body,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"{model_name}: missing EnvironmentConfigTableNoMod in appendix")
    initial_state_rows: list[VariableRow] = []
    parameter_rows: list[VariableRow] = []
    for raw_label, name, raw_interval in re.findall(
        r"(.+?)\s*&\s*\\code\{([^}]+)\}\s*&\s*\\code\{([^}]+)\}\s*\\\\",
        match.group(1),
    ):
        label = raw_label.strip()
        interval = _parse_code_value(raw_interval)
        if not (
            isinstance(interval, list)
            and len(interval) == 2
            and all(isinstance(value, (int, float)) for value in interval)
        ):
            raise ValueError(
                f"{model_name}: {name} allowed interval must be a numeric length-2 list"
            )
        row = VariableRow(label=label, name=name, allowed_intervals=interval)
        if label == r"\textemdash":
            initial_state_rows.append(row)
        else:
            parameter_rows.append(row)
    return tuple(initial_state_rows), tuple(parameter_rows)


def _parse_parameter_thresholds(
    body: str,
    *,
    model_name: str,
) -> Dict[str, ParameterThreshold]:
    match = re.search(
        r"\\begin\{ParameterSrdTable\}(.*?)\\end\{ParameterSrdTable\}",
        body,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"{model_name}: missing ParameterSrdTable in appendix")
    thresholds: Dict[str, ParameterThreshold] = {}
    for name, raw_srd, raw_absolute in re.findall(
        r"\\code\{([^}]+)\}\s*&\s*\\code\{([^}]+)\}\s*&\s*\\code\{([^}]+)\}\s*\\\\",
        match.group(1),
    ):
        srd = _parse_code_value(raw_srd)
        absolute = _parse_code_value(raw_absolute)
        if not isinstance(srd, (int, float)) or not isinstance(absolute, (int, float)):
            raise ValueError(f"{model_name}: thresholds for {name} must be numeric")
        thresholds[name] = ParameterThreshold(
            min_srd_distance=srd,
            min_abs_dist=absolute,
        )
    return thresholds


def _parse_simulation_properties(body: str, *, model_name: str) -> Dict[str, float | int]:
    match = re.search(
        r"\\begin\{SimulationPropertiesTable\}\{Simulation Properties\}(.*?)\\end\{SimulationPropertiesTable\}",
        body,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"{model_name}: missing SimulationPropertiesTable in appendix")
    properties: Dict[str, float | int] = {}
    for name, raw_value in re.findall(
        r"\\code\{([^}]+)\}\s*&\s*\\code\{([^}]+)\}\s*\\\\",
        match.group(1),
    ):
        value = _parse_code_value(raw_value)
        if not isinstance(value, (int, float)):
            raise ValueError(f"{model_name}: simulation property {name} must be numeric")
        properties[name] = value
    return properties


def _parse_signal_rows(body: str, *, model_name: str) -> tuple[SignalRow, ...]:
    match = re.search(
        r"\\begin\{MappingTable\}\{[^}]+\}(.*?)\\end\{MappingTable\}",
        body,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"{model_name}: missing MappingTable in appendix")
    rows: list[SignalRow] = []
    for raw_column, description, signal in re.findall(
        r"col(\d+):\s*(.*?)\s*&\s*\\code\{([^}]+)\}\s*\\\\",
        match.group(1),
    ):
        rows.append(
            SignalRow(
                column=int(raw_column),
                description=description.strip(),
                signal=signal,
            )
        )
    if not rows or rows[-1].signal != "time":
        raise ValueError(f"{model_name}: MappingTable must end with time")
    return tuple(rows)


def parse_appendix_environment(path: Path) -> Dict[str, AppendixEnvironmentSpec]:
    text = Path(path).read_text(encoding="utf-8")
    section_pattern = re.compile(
        r"\{\\LARGE\\bfseries\\texttt\{(?P<model>[^}]+)\}\\par\}(?P<body>.*?)(?=\n\\par\\bigskip\n\{\\LARGE\\bfseries\\texttt\{|\\tsenvAppendixEnvironmentEnd)",
        re.DOTALL,
    )
    specs: Dict[str, AppendixEnvironmentSpec] = {}
    for section in section_pattern.finditer(text):
        model_name = section.group("model")
        body = section.group("body")
        initial_state_rows, parameter_rows = _parse_variable_rows(
            body,
            model_name=model_name,
        )
        specs[model_name] = AppendixEnvironmentSpec(
            model_name=model_name,
            low_description=_parse_description(body, "Low", model_name=model_name),
            high_description=_parse_description(body, "High", model_name=model_name),
            initial_state_rows=initial_state_rows,
            parameter_rows=parameter_rows,
            parameter_thresholds=_parse_parameter_thresholds(body, model_name=model_name),
            simulation_properties=_parse_simulation_properties(body, model_name=model_name),
            signal_rows=_parse_signal_rows(body, model_name=model_name),
        )
    return specs


def _load_json_object(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _require_mapping(payload: Mapping[str, Any], key: str, *, path: Path) -> Dict[str, Any]:
    value = payload.get(key)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must define object key {key!r}")
    return value


def _ordered_existing_update(
    existing: Mapping[str, Any],
    ordered_names: Iterable[str],
    *,
    path: Path,
    label: str,
) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    seen: set[str] = set()
    for name in ordered_names:
        if name not in existing:
            raise ValueError(
                f"{path} missing {label} {name!r}; refusing to invent fields not documented in appendix"
            )
        out[name] = dict(existing[name])
        seen.add(name)
    for name, value in existing.items():
        if name not in seen:
            out[name] = value
    return out


def _observed_signals_description(signal_rows: tuple[SignalRow, ...]) -> str:
    return "\n".join(
        ["Observed Signals:"]
        + [
            f"col{row.column}: {row.description}"
            for row in signal_rows
        ]
    )


def update_description_levels_payload(
    payload: Dict[str, Any],
    spec: AppendixEnvironmentSpec,
    *,
    path: Path,
) -> Dict[str, Any]:
    out = dict(payload)
    textual_description = dict(_require_mapping(out, "textual_description", path=path))
    textual_description["low"] = spec.low_description
    textual_description["high"] = spec.high_description
    out["textual_description"] = textual_description
    out["internal_naming_to_agent_facing_parameter"] = {
        row.name: row.label
        for row in spec.parameter_rows
    }
    return out


def update_experiment_config_payload(
    payload: Dict[str, Any],
    spec: AppendixEnvironmentSpec,
    *,
    path: Path,
) -> Dict[str, Any]:
    out = dict(payload)
    exposed_variables = dict(_require_mapping(out, "exposed_variables", path=path))
    initial_state = _ordered_existing_update(
        _require_mapping(exposed_variables, "initial_state", path=path),
        [row.name for row in spec.initial_state_rows],
        path=path,
        label="initial_state",
    )
    for row in spec.initial_state_rows:
        initial_state[row.name]["allowed_intervals"] = row.allowed_intervals

    parameters = _ordered_existing_update(
        _require_mapping(exposed_variables, "parameters", path=path),
        [row.name for row in spec.parameter_rows],
        path=path,
        label="parameter",
    )
    for row in spec.parameter_rows:
        parameters[row.name]["allowed_intervals"] = row.allowed_intervals
        threshold = spec.parameter_thresholds.get(row.name)
        if threshold is None:
            raise ValueError(f"{spec.model_name}: missing threshold row for {row.name}")
        parameters[row.name]["min_srd_distance"] = threshold.min_srd_distance
        parameters[row.name]["min_abs_dist"] = threshold.min_abs_dist

    exposed_variables["initial_state"] = initial_state
    exposed_variables["parameters"] = parameters
    out["exposed_variables"] = exposed_variables
    for key in ("end_time_input_s", "sampling_rate_hz"):
        if key not in spec.simulation_properties:
            raise ValueError(f"{spec.model_name}: missing simulation property {key}")
        out[key] = spec.simulation_properties[key]
    return out


def write_json_if_changed(path: Path, payload: Mapping[str, Any]) -> bool:
    new_text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    old_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if old_text == new_text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


def update_model_from_appendix(
    model_name: str,
    *,
    project_root: Path = REPO_ROOT,
    appendix_path: Path | None = None,
) -> list[Path]:
    root = Path(project_root)
    appendix = appendix_path or root / "docs" / "appendix_environment.tex"
    specs = parse_appendix_environment(appendix)
    if model_name not in specs:
        raise ValueError(f"Model {model_name!r} is not documented in {appendix}")
    spec = specs[model_name]
    model_dir = root / "models" / "simulink" / model_name
    if not model_dir.is_dir():
        raise FileNotFoundError(f"Model directory not found: {model_dir}")

    description_path = model_dir / "description_levels.json"
    config_path = model_dir / "experiment_config.json"
    for path in (description_path, config_path):
        if not path.exists():
            raise FileNotFoundError(f"Required file not found: {path}")

    changed: list[Path] = []
    description_payload = update_description_levels_payload(
        _load_json_object(description_path),
        spec,
        path=description_path,
    )
    config_payload = update_experiment_config_payload(
        _load_json_object(config_path),
        spec,
        path=config_path,
    )
    if write_json_if_changed(description_path, description_payload):
        changed.append(description_path)
    if write_json_if_changed(config_path, config_payload):
        changed.append(config_path)
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Overwrite environment JSON entries from docs/appendix_environment.tex."
    )
    parser.add_argument("model", help="Model name under models/simulink/<MODEL>")
    parser.add_argument(
        "--project-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root. Defaults to this script's repository.",
    )
    parser.add_argument(
        "--appendix",
        type=Path,
        default=None,
        help="Path to appendix_environment.tex. Defaults to docs/appendix_environment.tex.",
    )
    args = parser.parse_args(argv)
    try:
        changed = update_model_from_appendix(
            args.model,
            project_root=args.project_root,
            appendix_path=args.appendix,
        )
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    if changed:
        for path in changed:
            print(f"updated {path}")
    else:
        print(f"{args.model}: already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
